# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login-qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1079, 609)
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        Dialog.setStyleSheet("background-color: #fff;\n"
"\n"
"font-family: OpenSans, \'Open Sans\', sans-serif;\n"
"\n"
"")
        self.LoginButton = QtWidgets.QPushButton(Dialog)
        self.LoginButton.setGeometry(QtCore.QRect(480, 350, 121, 41))
        self.LoginButton.setStyleSheet("border: 0;\n"
"  border-radius: 10px;\n"
"  border: 2px solid;\n"
"  border-color: #000;\n"
"  font-size: 16px;\n"
"  color: #000;\n"
"  background: #fff;\n"
"  letter-spacing: 0.0625rem;\n"
"  outline: none;")
        self.LoginButton.setObjectName("LoginButton")
        self.Username_label = QtWidgets.QLabel(Dialog)
        self.Username_label.setGeometry(QtCore.QRect(310, 199, 71, 21))
        self.Username_label.setStyleSheet("font-size: 14px;")
        self.Username_label.setObjectName("Username_label")
        self.Password_label = QtWidgets.QLabel(Dialog)
        self.Password_label.setGeometry(QtCore.QRect(310, 270, 81, 16))
        self.Password_label.setStyleSheet("font-size: 14px;")
        self.Password_label.setObjectName("Password_label")
        self.Username = QtWidgets.QLineEdit(Dialog)
        self.Username.setGeometry(QtCore.QRect(310, 220, 451, 41))
        self.Username.setStyleSheet("border-radius: 12px;\n"
"font-size: 16px;\n"
"border: 2px solid #000;\n"
"")
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(Dialog)
        self.Password.setGeometry(QtCore.QRect(310, 290, 451, 41))
        self.Password.setStyleSheet("border-radius: 12px;\n"
"font-size: 16px;\n"
"border: 2px solid #000;\n"
"")
        self.Password.setObjectName("Password")
        self.Message = QtWidgets.QFrame(Dialog)
        self.Message.setGeometry(QtCore.QRect(810, 30, 271, 71))
        self.Message.setStyleSheet("background: #fff; color: #fff;")
        self.Message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Message.setObjectName("Message")
        self.label = QtWidgets.QLabel(self.Message)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.label.setStyleSheet("font-size: 16px;")
        self.label.setObjectName("label")
        self.Registr = QtWidgets.QPushButton(Dialog)
        self.Registr.setGeometry(QtCore.QRect(440, 410, 211, 41))
        self.Registr.setStyleSheet("border: none;")
        self.Registr.setObjectName("Registr")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LoginButton.setText(_translate("Dialog", "login"))
        self.Username_label.setText(_translate("Dialog", "Username"))
        self.Password_label.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "text"))
        self.Registr.setText(_translate("Dialog", "Don\'t have an account? Sing up "))
