# Generated by Django 2.2.13 on 2021-01-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('extension', models.CharField(default='.txt', max_length=150)),
                ('image', models.ImageField(blank=True, default='file.jpg', null=True, upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ALL FILES',
                'verbose_name_plural': 'ALL FILES',
            },
        ),
    ]
